crowdfunding/config/routes.rb
Rails.application.routes.draw do
  
  get 'orders/new'
  get 'posts/new'
  get 'entrys/new'
  get 'sessions/new'
  
  root 'home#top'
  get '/home/about'
  get '/home/show'
  
  resources :entrys
  resources :orders
  resources :posts
  resources :users
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

crowdfunding/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

crowdfunding/app/models/entry.rb
class Entry < ApplicationRecord
end

crowdfunding/app/models/entrysheet.rb
class Entrysheet < ApplicationRecord
end

crowdfunding/app/models/order.rb
class Order < ApplicationRecord
end

crowdfunding/app/models/post.rb
class Post < ApplicationRecord
  validates :name, presence: true
  validates :description, presence: true
end

crowdfunding/app/models/sheet.rb
class Sheet < ApplicationRecord
end

crowdfunding/app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true
  
  has_secure_password
end

crowdfunding/app/controllers/entrys_controller.rb
class EntrysController < ApplicationController
  def new
    @entry = Entrysheet.new
  end
  
  def create
    
  end
end

crowdfunding/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
  
  def about
  end
  
  def show
    @posts = Post.all
  end
end

crowdfunding/app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def new
  end
  
  def create 
    @order = Order.new(user_id: @ccurent_user, post_id: params[:post_id])
      order.save
      redirect_to root_path
  end
end

crowdfunding/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
  end
  
  def create
  @post = Post.new(post_params)
  if @post.save
    redirect_to root_path, success: '登録が完了しました'
  else
    flash.now[:danger] = "登録に失敗しました"
    render :new
  end
  end
  
  
  def show
  end
  
  private
  def post_params
    params.require(:post).permit(:name, :description)
  end
  
  
  
end

crowdfunding/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to root_path, success: 'ログインに成功しました'
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end
  
  def destroy
    log_out
    redirect_to root_url, info: 'ログアウトしました'
  end


  private
  def log_in(user)
    session[:user_id] = user.id
  end
  
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

crowdfunding/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
  @user = User.new(user_params)
  if @user.save
    redirect_to root_path, success: '登録が完了しました'
  else
    flash.now[:danger] = "登録に失敗しました"
    render :new
  end
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

crowdfunding/app/helpers/application_helper.rb
module ApplicationHelper
  
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end
  
  
end

crowdfunding/app/helpers/entrys_helper.rb
module EntrysHelper
end

crowdfunding/app/helpers/home_helper.rb
module HomeHelper
end

crowdfunding/app/helpers/orders_helper.rb
module OrdersHelper
end

crowdfunding/app/helpers/posts_helper.rb
module PostsHelper
end

crowdfunding/app/helpers/sessions_helper.rb
module SessionsHelper
end

crowdfunding/app/helpers/user_helper.rb
module UserHelper
end

crowdfunding/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crowdfunding</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
  <header>
  <div class="header-logo">
    <%= link_to 'Movie film',root_path %>
  </div>
  <ul class="header-menus">
    
    <li><%= link_to 'crowdfundingとは', home_about_path %></li>
    
    <li>
      <form class="project_search" id="project_search" action="/portals/search" accept-charset="UTF-8" method="get"><input name="utf8" type="hidden" value="✓"><dl class="general_search">
<dt>
<input placeholder="Search Word" type="text" name="q[title_or_planner_name_cont]" id="q_title_or_planner_name_cont">
</dt>
<dd>
<button name="button" type="submit"><!--?xml version="1.0" encoding="UTF-8"?-->
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 50 50" version="1.1" width="18px" height="18px" xmlns:xlink="http://www.w3.org/1999/xlink">
<g id="surface1">
<path style=" " d="M 21 3 C 11.601563 3 4 10.601563 4 20 C 4 29.398438 11.601563 37 21 37 C 24.355469 37 27.460938 36.015625 30.09375 34.34375 L 42.375 46.625 L 46.625 42.375 L 34.5 30.28125 C 36.679688 27.421875 38 23.878906 38 20 C 38 10.601563 30.398438 3 21 3 Z M 21 7 C 28.199219 7 34 12.800781 34 20 C 34 27.199219 28.199219 33 21 33 C 13.800781 33 8 27.199219 8 20 C 8 12.800781 13.800781 7 21 7 Z "></path>
</g>
</svg>

</button></dd>
</dl>
</form>
      
    </li>

    <li><%= link_to 'プロジェクトにエントリー', new_entry_path %></li>
    <li><%= link_to '買い物かご', '#' %></li>
    <li><%= link_to '新規登録', new_user_path %></li>
    <li><%= link_to 'ログイン', login_path %></li>
    <li><%= link_to 'ログアウト' %></li>
    <li><%= link_to '商品登録', new_post_path %></li>
  </ul>
</header>

<footer>
<nav>
<a href="#">トップページ</a> 
</nav>
<p>Crowd funding Copyright 2019</p>
</footer>

  <body>
    
    <% flash.each do |key, value| %>
       <div class="alert alert-<%= key %>" role="alert"><%= value %></div>
    <% end %>


    <%= yield %>
    
    <script>
      $(function(){
        $(".alert").fadeOut(5000);
      });
   </script>

  </body>
</html>